name: Auto translate
on:
  push:
    branches:
      - dev
    paths:
      - 'locale/en-us/**'
      - 'dialog/en-us/**'
      - 'vocab/en-us/**'
  workflow_dispatch:

jobs:
  autotranslate:
    if: "! contains(toJSON(github.event.commits.*.message), 'autotranslate')"
    env:
      API_KEY: ${{secrets.DL_API_KEY}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install Translate Tools
        run: |
          python -m pip install ovos-translate-plugin-deepl ovos-utils
      - name: Auto Translate
        run: |
          python scripts/translate.py
      - name: Commit to dev
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: autotranslate
          branch: dev
